
export const bikes = [
    {
        brand: 'Specialized',
        model: 'S-Works Enduro',
        size: 'S',
        category: 'mountain',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Specialized',
        model: 'S-Works Enduro',
        size: 'L',
        category: 'mountain',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Specialized',
        model: 'Turbo Levo Comp',
        size: 'M',
        category: 'mountain',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Levo ofrece una increíble potencia para recorrer más senderos gracias a una combinación inigualable entre calidad de conducción, potencia utilizable y autonomía. Es el refinamiento, la implementación y la amplificación de todo lo que sabemos sobre el mountain bike: una obsesión de 40 años en crear las mejores bicis de mountain del mundo. Desde su presentación, la Turbo Levo ha marcado el camino a seguir, es la meta por alcanzar de cualquier e-mountain bike, y esta nueva bicicleta vuelve a subir el listón.',
        images: ['https://assets.specialized.com/i/specialized/96422-50_LEVO-COMP-CARBON-BLK-LTSIL-BLK_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Specialized',
        model: 'Kenevo Comp',
        size: 'L',
        category: 'mountain',
        class: 'b',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La Kenevo es la eMTB con mayor rendimiento que puedes encontrar, con 180 mm de suspensión delantera y trasera, el motor más suave y potente disponible, y ahora con más kilómetros por carga que nunca. Nuestro modelo Kenevo Comp combina toda esa tecnología con un conjunto de componentes inteligentemente escogidos que soportarán las condiciones y a los usuarios más exigentes.',
        images: ['https://assets.specialized.com/i/specialized/98022-50_KENEVO-COMP-6FATTIE-LGNBLU-BLK_HERO?bg=rgb(241,241,241)&w=1600&h=900&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Specialized',
        model: 'Rockhopper Sport 29',
        size: 'M',
        category: 'mountain',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Lista para el juego con los frenos de disco hidráulicos Shimano MT200, transmisión MicroSHIFT y una horquilla SR Suntour XCM hecha para el ajetreo; la Rockhopper Sport puede lograr la victoria cualquier domingo, ¡y el resto de la semana también!.',
        images: ['https://assets.specialized.com/i/specialized/91822-66_ROCKHOPPER-SPORT-29-FSTGRN-OIS_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Specialized',
        model: 'Chisel',
        size: 'L',
        category: 'mountain',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }
    ,
    {
        brand: 'Specialized',
        model: 'SPARK RC SL EVO AXS',
        size: 'L',
        category: 'mountain',
        class: 'b',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }

    , {
        brand: 'Scott',
        model: 'S-Works Enduro',
        size: 'S',
        category: 'mountain',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Scott',
        model: 'S-Works Enduro',
        size: 'L',
        category: 'mountain',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Scott',
        model: 'Turbo Levo Comp',
        size: 'M',
        category: 'mountain',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Levo ofrece una increíble potencia para recorrer más senderos gracias a una combinación inigualable entre calidad de conducción, potencia utilizable y autonomía. Es el refinamiento, la implementación y la amplificación de todo lo que sabemos sobre el mountain bike: una obsesión de 40 años en crear las mejores bicis de mountain del mundo. Desde su presentación, la Turbo Levo ha marcado el camino a seguir, es la meta por alcanzar de cualquier e-mountain bike, y esta nueva bicicleta vuelve a subir el listón.',
        images: ['https://assets.specialized.com/i/specialized/96422-50_LEVO-COMP-CARBON-BLK-LTSIL-BLK_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Scott',
        model: 'Kenevo Comp',
        size: 'L',
        category: 'mountain',
        class: 'b',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La Kenevo es la eMTB con mayor rendimiento que puedes encontrar, con 180 mm de suspensión delantera y trasera, el motor más suave y potente disponible, y ahora con más kilómetros por carga que nunca. Nuestro modelo Kenevo Comp combina toda esa tecnología con un conjunto de componentes inteligentemente escogidos que soportarán las condiciones y a los usuarios más exigentes.',
        images: ['https://assets.specialized.com/i/specialized/98022-50_KENEVO-COMP-6FATTIE-LGNBLU-BLK_HERO?bg=rgb(241,241,241)&w=1600&h=900&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Scott',
        model: 'Rockhopper Sport 29',
        size: 'M',
        category: 'mountain',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Lista para el juego con los frenos de disco hidráulicos Shimano MT200, transmisión MicroSHIFT y una horquilla SR Suntour XCM hecha para el ajetreo; la Rockhopper Sport puede lograr la victoria cualquier domingo, ¡y el resto de la semana también!.',
        images: ['https://assets.specialized.com/i/specialized/91822-66_ROCKHOPPER-SPORT-29-FSTGRN-OIS_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Scott',
        model: 'Chisel',
        size: 'L',
        category: 'mountain',
        class: 'b',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }

    ,
    {
        brand: 'Scott',
        model: 'SPARK RC SL EVO AXS',
        size: 'L',
        category: 'mountain',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }

    ,
    {
        brand: 'Kross',
        model: 'SPARK RC SL EVO AXS',
        size: 'L',
        category: 'mountain',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }

    , {
        brand: 'Kross',
        model: 'S-Works Enduro',
        size: 'S',
        category: 'mountain',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Kross',
        model: 'S-Works Enduro',
        size: 'L',
        category: 'mountain',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Kross',
        model: 'Turbo Levo Comp',
        size: 'M',
        category: 'mountain',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Levo ofrece una increíble potencia para recorrer más senderos gracias a una combinación inigualable entre calidad de conducción, potencia utilizable y autonomía. Es el refinamiento, la implementación y la amplificación de todo lo que sabemos sobre el mountain bike: una obsesión de 40 años en crear las mejores bicis de mountain del mundo. Desde su presentación, la Turbo Levo ha marcado el camino a seguir, es la meta por alcanzar de cualquier e-mountain bike, y esta nueva bicicleta vuelve a subir el listón.',
        images: ['https://assets.specialized.com/i/specialized/96422-50_LEVO-COMP-CARBON-BLK-LTSIL-BLK_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Kross',
        model: 'Kenevo Comp',
        size: 'L',
        category: 'mountain',
        class: 'b',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La Kenevo es la eMTB con mayor rendimiento que puedes encontrar, con 180 mm de suspensión delantera y trasera, el motor más suave y potente disponible, y ahora con más kilómetros por carga que nunca. Nuestro modelo Kenevo Comp combina toda esa tecnología con un conjunto de componentes inteligentemente escogidos que soportarán las condiciones y a los usuarios más exigentes.',
        images: ['https://assets.specialized.com/i/specialized/98022-50_KENEVO-COMP-6FATTIE-LGNBLU-BLK_HERO?bg=rgb(241,241,241)&w=1600&h=900&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Kross',
        model: 'Rockhopper Sport 29',
        size: 'M',
        category: 'mountain',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Lista para el juego con los frenos de disco hidráulicos Shimano MT200, transmisión MicroSHIFT y una horquilla SR Suntour XCM hecha para el ajetreo; la Rockhopper Sport puede lograr la victoria cualquier domingo, ¡y el resto de la semana también!.',
        images: ['https://assets.specialized.com/i/specialized/91822-66_ROCKHOPPER-SPORT-29-FSTGRN-OIS_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Kross',
        model: 'Chisel',
        size: 'L',
        category: 'mountain',
        class: 'b',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }
    ,
    {
        brand: 'Kross',
        model: 'SPARK RC SL EVO AXS',
        size: 'L',
        category: 'mountain',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }

    ,
    {
        brand: 'Specialized',
        model: 'S-Works Enduro',
        size: 'S',
        category: 'city',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Specialized',
        model: 'S-Works Enduro',
        size: 'L',
        category: 'city',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Specialized',
        model: 'Turbo Levo Comp',
        size: 'M',
        category: 'city',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Levo ofrece una increíble potencia para recorrer más senderos gracias a una combinación inigualable entre calidad de conducción, potencia utilizable y autonomía. Es el refinamiento, la implementación y la amplificación de todo lo que sabemos sobre el mountain bike: una obsesión de 40 años en crear las mejores bicis de mountain del mundo. Desde su presentación, la Turbo Levo ha marcado el camino a seguir, es la meta por alcanzar de cualquier e-mountain bike, y esta nueva bicicleta vuelve a subir el listón.',
        images: ['https://assets.specialized.com/i/specialized/96422-50_LEVO-COMP-CARBON-BLK-LTSIL-BLK_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Specialized',
        model: 'Kenevo Comp',
        size: 'L',
        category: 'city',
        class: 'b',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La Kenevo es la eMTB con mayor rendimiento que puedes encontrar, con 180 mm de suspensión delantera y trasera, el motor más suave y potente disponible, y ahora con más kilómetros por carga que nunca. Nuestro modelo Kenevo Comp combina toda esa tecnología con un conjunto de componentes inteligentemente escogidos que soportarán las condiciones y a los usuarios más exigentes.',
        images: ['https://assets.specialized.com/i/specialized/98022-50_KENEVO-COMP-6FATTIE-LGNBLU-BLK_HERO?bg=rgb(241,241,241)&w=1600&h=900&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Specialized',
        model: 'Rockhopper Sport 29',
        size: 'M',
        category: 'city',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Lista para el juego con los frenos de disco hidráulicos Shimano MT200, transmisión MicroSHIFT y una horquilla SR Suntour XCM hecha para el ajetreo; la Rockhopper Sport puede lograr la victoria cualquier domingo, ¡y el resto de la semana también!.',
        images: ['https://assets.specialized.com/i/specialized/91822-66_ROCKHOPPER-SPORT-29-FSTGRN-OIS_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Specialized',
        model: 'Chisel',
        size: 'L',
        category: 'city',
        class: 'b',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }
    ,
    {
        brand: 'Specialized',
        model: 'SPARK RC SL EVO AXS',
        size: 'L',
        category: 'city',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }


    ,
    {
        brand: 'Scott',
        model: 'S-Works Enduro',
        size: 'S',
        category: 'city',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Scott',
        model: 'S-Works Enduro',
        size: 'L',
        category: 'city',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Scott',
        model: 'Turbo Levo Comp',
        size: 'M',
        category: 'city',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Levo ofrece una increíble potencia para recorrer más senderos gracias a una combinación inigualable entre calidad de conducción, potencia utilizable y autonomía. Es el refinamiento, la implementación y la amplificación de todo lo que sabemos sobre el mountain bike: una obsesión de 40 años en crear las mejores bicis de mountain del mundo. Desde su presentación, la Turbo Levo ha marcado el camino a seguir, es la meta por alcanzar de cualquier e-mountain bike, y esta nueva bicicleta vuelve a subir el listón.',
        images: ['https://assets.specialized.com/i/specialized/96422-50_LEVO-COMP-CARBON-BLK-LTSIL-BLK_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Scott',
        model: 'Kenevo Comp',
        size: 'L',
        category: 'city',
        class: 'b',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La Kenevo es la eMTB con mayor rendimiento que puedes encontrar, con 180 mm de suspensión delantera y trasera, el motor más suave y potente disponible, y ahora con más kilómetros por carga que nunca. Nuestro modelo Kenevo Comp combina toda esa tecnología con un conjunto de componentes inteligentemente escogidos que soportarán las condiciones y a los usuarios más exigentes.',
        images: ['https://assets.specialized.com/i/specialized/98022-50_KENEVO-COMP-6FATTIE-LGNBLU-BLK_HERO?bg=rgb(241,241,241)&w=1600&h=900&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Scott',
        model: 'Rockhopper Sport 29',
        size: 'M',
        category: 'city',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Lista para el juego con los frenos de disco hidráulicos Shimano MT200, transmisión MicroSHIFT y una horquilla SR Suntour XCM hecha para el ajetreo; la Rockhopper Sport puede lograr la victoria cualquier domingo, ¡y el resto de la semana también!.',
        images: ['https://assets.specialized.com/i/specialized/91822-66_ROCKHOPPER-SPORT-29-FSTGRN-OIS_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Scott',
        model: 'Chisel',
        size: 'L',
        category: 'city',
        class: 'b',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }
    ,
    {
        brand: 'Scott',
        model: 'SPARK RC SL EVO AXS',
        size: 'L',
        category: 'city',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }

    ,
    {
        brand: 'Kross',
        model: 'S-Works Enduro',
        size: 'S',
        category: 'city',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Kross',
        model: 'S-Works Enduro',
        size: 'L',
        category: 'city',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Kross',
        model: 'Turbo Levo Comp',
        size: 'M',
        category: 'city',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Levo ofrece una increíble potencia para recorrer más senderos gracias a una combinación inigualable entre calidad de conducción, potencia utilizable y autonomía. Es el refinamiento, la implementación y la amplificación de todo lo que sabemos sobre el mountain bike: una obsesión de 40 años en crear las mejores bicis de mountain del mundo. Desde su presentación, la Turbo Levo ha marcado el camino a seguir, es la meta por alcanzar de cualquier e-mountain bike, y esta nueva bicicleta vuelve a subir el listón.',
        images: ['https://assets.specialized.com/i/specialized/96422-50_LEVO-COMP-CARBON-BLK-LTSIL-BLK_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Kross',
        model: 'Kenevo Comp',
        size: 'L',
        category: 'city',
        class: 'b',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La Kenevo es la eMTB con mayor rendimiento que puedes encontrar, con 180 mm de suspensión delantera y trasera, el motor más suave y potente disponible, y ahora con más kilómetros por carga que nunca. Nuestro modelo Kenevo Comp combina toda esa tecnología con un conjunto de componentes inteligentemente escogidos que soportarán las condiciones y a los usuarios más exigentes.',
        images: ['https://assets.specialized.com/i/specialized/98022-50_KENEVO-COMP-6FATTIE-LGNBLU-BLK_HERO?bg=rgb(241,241,241)&w=1600&h=900&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Kross',
        model: 'Rockhopper Sport 29',
        size: 'M',
        category: 'city',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Lista para el juego con los frenos de disco hidráulicos Shimano MT200, transmisión MicroSHIFT y una horquilla SR Suntour XCM hecha para el ajetreo; la Rockhopper Sport puede lograr la victoria cualquier domingo, ¡y el resto de la semana también!.',
        images: ['https://assets.specialized.com/i/specialized/91822-66_ROCKHOPPER-SPORT-29-FSTGRN-OIS_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Kross',
        model: 'Chisel',
        size: 'L',
        category: 'city',
        class: 'b',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }
    ,
    {
        brand: 'Kross',
        model: 'SPARK RC SL EVO AXS',
        size: 'L',
        category: 'city',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }

    ,
    {
        brand: 'Specialized',
        model: 'S-Works Enduro',
        size: 'S',
        category: 'electric',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Specialized',
        model: 'S-Works Enduro',
        size: 'L',
        category: 'electric',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Specialized',
        model: 'Turbo Levo Comp',
        size: 'M',
        category: 'electric',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Levo ofrece una increíble potencia para recorrer más senderos gracias a una combinación inigualable entre calidad de conducción, potencia utilizable y autonomía. Es el refinamiento, la implementación y la amplificación de todo lo que sabemos sobre el mountain bike: una obsesión de 40 años en crear las mejores bicis de mountain del mundo. Desde su presentación, la Turbo Levo ha marcado el camino a seguir, es la meta por alcanzar de cualquier e-mountain bike, y esta nueva bicicleta vuelve a subir el listón.',
        images: ['https://assets.specialized.com/i/specialized/96422-50_LEVO-COMP-CARBON-BLK-LTSIL-BLK_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Specialized',
        model: 'Kenevo Comp',
        size: 'L',
        category: 'electric',
        class: 'b',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La Kenevo es la eMTB con mayor rendimiento que puedes encontrar, con 180 mm de suspensión delantera y trasera, el motor más suave y potente disponible, y ahora con más kilómetros por carga que nunca. Nuestro modelo Kenevo Comp combina toda esa tecnología con un conjunto de componentes inteligentemente escogidos que soportarán las condiciones y a los usuarios más exigentes.',
        images: ['https://assets.specialized.com/i/specialized/98022-50_KENEVO-COMP-6FATTIE-LGNBLU-BLK_HERO?bg=rgb(241,241,241)&w=1600&h=900&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Specialized',
        model: 'Rockhopper Sport 29',
        size: 'M',
        category: 'electric',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Lista para el juego con los frenos de disco hidráulicos Shimano MT200, transmisión MicroSHIFT y una horquilla SR Suntour XCM hecha para el ajetreo; la Rockhopper Sport puede lograr la victoria cualquier domingo, ¡y el resto de la semana también!.',
        images: ['https://assets.specialized.com/i/specialized/91822-66_ROCKHOPPER-SPORT-29-FSTGRN-OIS_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Specialized',
        model: 'Chisel',
        size: 'L',
        category: 'electric',
        class: 'b',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }
    ,
    {
        brand: 'Specialized',
        model: 'SPARK RC SL EVO AXS',
        size: 'L',
        category: 'electric',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }

    ,
    {
        brand: 'Scott',
        model: 'S-Works Enduro',
        size: 'S',
        category: 'electric',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Scott',
        model: 'S-Works Enduro',
        size: 'L',
        category: 'electric',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Scott',
        model: 'Turbo Levo Comp',
        size: 'M',
        category: 'electric',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Levo ofrece una increíble potencia para recorrer más senderos gracias a una combinación inigualable entre calidad de conducción, potencia utilizable y autonomía. Es el refinamiento, la implementación y la amplificación de todo lo que sabemos sobre el mountain bike: una obsesión de 40 años en crear las mejores bicis de mountain del mundo. Desde su presentación, la Turbo Levo ha marcado el camino a seguir, es la meta por alcanzar de cualquier e-mountain bike, y esta nueva bicicleta vuelve a subir el listón.',
        images: ['https://assets.specialized.com/i/specialized/96422-50_LEVO-COMP-CARBON-BLK-LTSIL-BLK_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Scott',
        model: 'Kenevo Comp',
        size: 'L',
        category: 'electric',
        class: 'b',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La Kenevo es la eMTB con mayor rendimiento que puedes encontrar, con 180 mm de suspensión delantera y trasera, el motor más suave y potente disponible, y ahora con más kilómetros por carga que nunca. Nuestro modelo Kenevo Comp combina toda esa tecnología con un conjunto de componentes inteligentemente escogidos que soportarán las condiciones y a los usuarios más exigentes.',
        images: ['https://assets.specialized.com/i/specialized/98022-50_KENEVO-COMP-6FATTIE-LGNBLU-BLK_HERO?bg=rgb(241,241,241)&w=1600&h=900&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Scott',
        model: 'Rockhopper Sport 29',
        size: 'M',
        category: 'electric',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Lista para el juego con los frenos de disco hidráulicos Shimano MT200, transmisión MicroSHIFT y una horquilla SR Suntour XCM hecha para el ajetreo; la Rockhopper Sport puede lograr la victoria cualquier domingo, ¡y el resto de la semana también!.',
        images: ['https://assets.specialized.com/i/specialized/91822-66_ROCKHOPPER-SPORT-29-FSTGRN-OIS_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Scott',
        model: 'Chisel',
        size: 'L',
        category: 'electric',
        class: 'b',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }
    ,
    {
        brand: 'Scott',
        model: 'SPARK RC SL EVO AXS',
        size: 'L',
        category: 'electric',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }

    ,
    {
        brand: 'Kross',
        model: 'S-Works Enduro',
        size: 'S',
        category: 'electric',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Kross',
        model: 'S-Works Enduro',
        size: 'L',
        category: 'electric',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Kross',
        model: 'Turbo Levo Comp',
        size: 'M',
        category: 'electric',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Levo ofrece una increíble potencia para recorrer más senderos gracias a una combinación inigualable entre calidad de conducción, potencia utilizable y autonomía. Es el refinamiento, la implementación y la amplificación de todo lo que sabemos sobre el mountain bike: una obsesión de 40 años en crear las mejores bicis de mountain del mundo. Desde su presentación, la Turbo Levo ha marcado el camino a seguir, es la meta por alcanzar de cualquier e-mountain bike, y esta nueva bicicleta vuelve a subir el listón.',
        images: ['https://assets.specialized.com/i/specialized/96422-50_LEVO-COMP-CARBON-BLK-LTSIL-BLK_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Kross',
        model: 'Kenevo Comp',
        size: 'L',
        category: 'electric',
        class: 'b',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La Kenevo es la eMTB con mayor rendimiento que puedes encontrar, con 180 mm de suspensión delantera y trasera, el motor más suave y potente disponible, y ahora con más kilómetros por carga que nunca. Nuestro modelo Kenevo Comp combina toda esa tecnología con un conjunto de componentes inteligentemente escogidos que soportarán las condiciones y a los usuarios más exigentes.',
        images: ['https://assets.specialized.com/i/specialized/98022-50_KENEVO-COMP-6FATTIE-LGNBLU-BLK_HERO?bg=rgb(241,241,241)&w=1600&h=900&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Kross',
        model: 'Rockhopper Sport 29',
        size: 'M',
        category: 'electric',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Lista para el juego con los frenos de disco hidráulicos Shimano MT200, transmisión MicroSHIFT y una horquilla SR Suntour XCM hecha para el ajetreo; la Rockhopper Sport puede lograr la victoria cualquier domingo, ¡y el resto de la semana también!.',
        images: ['https://assets.specialized.com/i/specialized/91822-66_ROCKHOPPER-SPORT-29-FSTGRN-OIS_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Kross',
        model: 'Chisel',
        size: 'L',
        category: 'electric',
        class: 'b',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }
    ,
    {
        brand: 'Kross',
        model: 'SPARK RC SL EVO AXS',
        size: 'L',
        category: 'electric',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }

    ,
    {
        brand: 'Specialized',
        model: 'S-Works Enduro',
        size: 'S',
        category: 'road',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Specialized',
        model: 'S-Works Enduro',
        size: 'L',
        category: 'road',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Specialized',
        model: 'Turbo Levo Comp',
        size: 'M',
        category: 'road',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Levo ofrece una increíble potencia para recorrer más senderos gracias a una combinación inigualable entre calidad de conducción, potencia utilizable y autonomía. Es el refinamiento, la implementación y la amplificación de todo lo que sabemos sobre el mountain bike: una obsesión de 40 años en crear las mejores bicis de mountain del mundo. Desde su presentación, la Turbo Levo ha marcado el camino a seguir, es la meta por alcanzar de cualquier e-mountain bike, y esta nueva bicicleta vuelve a subir el listón.',
        images: ['https://assets.specialized.com/i/specialized/96422-50_LEVO-COMP-CARBON-BLK-LTSIL-BLK_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Specialized',
        model: 'Kenevo Comp',
        size: 'L',
        category: 'road',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La Kenevo es la eMTB con mayor rendimiento que puedes encontrar, con 180 mm de suspensión delantera y trasera, el motor más suave y potente disponible, y ahora con más kilómetros por carga que nunca. Nuestro modelo Kenevo Comp combina toda esa tecnología con un conjunto de componentes inteligentemente escogidos que soportarán las condiciones y a los usuarios más exigentes.',
        images: ['https://assets.specialized.com/i/specialized/98022-50_KENEVO-COMP-6FATTIE-LGNBLU-BLK_HERO?bg=rgb(241,241,241)&w=1600&h=900&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Specialized',
        model: 'Rockhopper Sport 29',
        size: 'M',
        category: 'road',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Lista para el juego con los frenos de disco hidráulicos Shimano MT200, transmisión MicroSHIFT y una horquilla SR Suntour XCM hecha para el ajetreo; la Rockhopper Sport puede lograr la victoria cualquier domingo, ¡y el resto de la semana también!.',
        images: ['https://assets.specialized.com/i/specialized/91822-66_ROCKHOPPER-SPORT-29-FSTGRN-OIS_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Specialized',
        model: 'Chisel',
        size: 'L',
        category: 'road',
        class: 'b',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }
    ,
    {
        brand: 'Specialized',
        model: 'SPARK RC SL EVO AXS',
        size: 'L',
        category: 'road',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }

    ,
    {
        brand: 'Scott',
        model: 'S-Works Enduro',
        size: 'S',
        category: 'road',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Scott',
        model: 'S-Works Enduro',
        size: 'L',
        category: 'road',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Scott',
        model: 'Turbo Levo Comp',
        size: 'M',
        category: 'road',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Levo ofrece una increíble potencia para recorrer más senderos gracias a una combinación inigualable entre calidad de conducción, potencia utilizable y autonomía. Es el refinamiento, la implementación y la amplificación de todo lo que sabemos sobre el mountain bike: una obsesión de 40 años en crear las mejores bicis de mountain del mundo. Desde su presentación, la Turbo Levo ha marcado el camino a seguir, es la meta por alcanzar de cualquier e-mountain bike, y esta nueva bicicleta vuelve a subir el listón.',
        images: ['https://assets.specialized.com/i/specialized/96422-50_LEVO-COMP-CARBON-BLK-LTSIL-BLK_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Scott',
        model: 'Kenevo Comp',
        size: 'L',
        category: 'road',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La Kenevo es la eMTB con mayor rendimiento que puedes encontrar, con 180 mm de suspensión delantera y trasera, el motor más suave y potente disponible, y ahora con más kilómetros por carga que nunca. Nuestro modelo Kenevo Comp combina toda esa tecnología con un conjunto de componentes inteligentemente escogidos que soportarán las condiciones y a los usuarios más exigentes.',
        images: ['https://assets.specialized.com/i/specialized/98022-50_KENEVO-COMP-6FATTIE-LGNBLU-BLK_HERO?bg=rgb(241,241,241)&w=1600&h=900&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Scott',
        model: 'Rockhopper Sport 29',
        size: 'M',
        category: 'road',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Lista para el juego con los frenos de disco hidráulicos Shimano MT200, transmisión MicroSHIFT y una horquilla SR Suntour XCM hecha para el ajetreo; la Rockhopper Sport puede lograr la victoria cualquier domingo, ¡y el resto de la semana también!.',
        images: ['https://assets.specialized.com/i/specialized/91822-66_ROCKHOPPER-SPORT-29-FSTGRN-OIS_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Scott',
        model: 'Chisel',
        size: 'L',
        category: 'road',
        class: 'b',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }
    ,
    {
        brand: 'Scott',
        model: 'SPARK RC SL EVO AXS',
        size: 'L',
        category: 'road',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }

    ,
    {
        brand: 'Kross',
        model: 'S-Works Enduro',
        size: 'S',
        category: 'road',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Kross',
        model: 'S-Works Enduro',
        size: 'L',
        category: 'road',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Si buscas montar la bicicleta de enduro más rápida y eficiente, no puedes hacerlo mejor que con el modelo que define el género. La S-Works Enduro se enfrenta felizmente a todos los terrenos.',
        images: ['https://assets.specialized.com/i/specialized/93622-00_ENDURO-SW-BLKLQDMET-BLKLQDMET-SILDST_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto',],
        avaiable: true,
    },
    {
        brand: 'Kross',
        model: 'Turbo Levo Comp',
        size: 'M',
        category: 'road',
        class: 'a',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Levo ofrece una increíble potencia para recorrer más senderos gracias a una combinación inigualable entre calidad de conducción, potencia utilizable y autonomía. Es el refinamiento, la implementación y la amplificación de todo lo que sabemos sobre el mountain bike: una obsesión de 40 años en crear las mejores bicis de mountain del mundo. Desde su presentación, la Turbo Levo ha marcado el camino a seguir, es la meta por alcanzar de cualquier e-mountain bike, y esta nueva bicicleta vuelve a subir el listón.',
        images: ['https://assets.specialized.com/i/specialized/96422-50_LEVO-COMP-CARBON-BLK-LTSIL-BLK_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Kross',
        model: 'Kenevo Comp',
        size: 'L',
        category: 'road',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La Kenevo es la eMTB con mayor rendimiento que puedes encontrar, con 180 mm de suspensión delantera y trasera, el motor más suave y potente disponible, y ahora con más kilómetros por carga que nunca. Nuestro modelo Kenevo Comp combina toda esa tecnología con un conjunto de componentes inteligentemente escogidos que soportarán las condiciones y a los usuarios más exigentes.',
        images: ['https://assets.specialized.com/i/specialized/98022-50_KENEVO-COMP-6FATTIE-LGNBLU-BLK_HERO?bg=rgb(241,241,241)&w=1600&h=900&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Kross',
        model: 'Rockhopper Sport 29',
        size: 'M',
        category: 'road',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'Lista para el juego con los frenos de disco hidráulicos Shimano MT200, transmisión MicroSHIFT y una horquilla SR Suntour XCM hecha para el ajetreo; la Rockhopper Sport puede lograr la victoria cualquier domingo, ¡y el resto de la semana también!.',
        images: ['https://assets.specialized.com/i/specialized/91822-66_ROCKHOPPER-SPORT-29-FSTGRN-OIS_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    },
    {
        brand: 'Kross',
        model: 'Chisel',
        size: 'L',
        category: 'road',
        class: 'b',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }
    ,
    {
        brand: 'Kross',
        model: 'SPARK RC SL EVO AXS',
        size: 'L',
        category: 'road',
        class: 'c',
        dayPrice: 10,
        specs: ['spec1', 'spec2'],
        description: 'La nueva Chisel ha sido especialmente diseñada para afrontar los trazados modernos de cross country y circuitos de competición con la mayor velocidad. De hecho, comparte muchas de las mismas características modernas que su hermana la Epic Hardtail, pero en un conjunto más económico , Lo que la convierte en la bicicleta rígida de aluminio más eficiente y capaz que existe.',
        images: ['https://assets.specialized.com/i/specialized/91722-70_CHISEL-HT-MRN-ICEPPYA_HERO?bg=rgb(241,241,241)&w=2500&h=1406&fmt=auto'],
        avaiable: true,
    }
]
/**
 {
        brand: ,
        model: ,
        size: ,
        category: ,
        class: ,
        dayPrice: ,
        specs: [],
        description: ,
        images: [],
        avaiable: ,
}

     //   rented: { type: [Date], index: true },


 */





